export const APP_VERSION = '5.3.0';
export const GROK_BASE_URL = "https://api.x.ai/v1/chat/completions";

export const i18n = {
  en: {
    settings: 'Settings', home: 'Home', meds: 'Medications', logAction: 'Log Intake', plans: 'Plans',
    dueToday: 'Due Today', noPlans: 'No plans found. Create one!',
    noUpcoming: "No upcoming plans",
    recentActivity: "Recent Activity",
    loggedActivity: 'Today\'s Activity', noLogsToday: 'No intake logged today.',
    recentMetrics: 'Recent Metrics', noMetrics: 'No metrics recorded yet.',
    scheduled: 'Scheduled', completed: '✅ Completed', skipped: '❌ Skipped', skip: 'Skip', dueTodayBadge: '• Due Today', taken: 'taken', weight: 'Weight',
    pastDue: 'PAST DUE', missedTitle: 'Missed Appointments',
    addMedication: 'Add Medication', nameLbl: 'Name', defaultDose: 'Default Dose', unitLbl: 'Unit', formatLbl: 'Format',
    saveMedication: 'Save Medication', cancel: 'Cancel', yourMedications: 'Your Medications',
    noMedsFound: 'No medications found. Add one!', delete: 'Delete', addBtn: '+ Add New',
    viewSideEffects: '⚠️ View Side Effects', translateAdverse: '🌐 Translate to German',
    createSchedule: 'Create Plan', selectMed: 'Select Medication', timeOfDay: 'Time',
    dose: 'Dose', savePlan: 'Save Plan', yourSchedule: 'Your Daily Schedule',
    noSchedule: 'No schedule created.', remove: 'Remove', newPlan: '+ New',
    takes: 'Takes', at: 'at', appleCalendar: '+ Apple Calendar', chooseOption: '-- Choose Option --',
    addMedFirst: 'Add a medication first.',
    logIntake: 'Log Intake', addMedFirst2: 'Please add a medication first.',
    amountTaken: 'Amount Taken', quantity: 'Quantity', recordIntake: 'Save Intake',
    logDateTime: 'Date & Time',
    otherMed: 'Other (Manual Entry)',
    logMetric: 'Record Body Metric', metricType: 'Metric Type', bodyWeight: 'Body Weight (kg)',
    bloodPressure: 'Blood Pressure (mmHg)', valueLbl: 'Value', saveMetric: 'Save Metric',
    dataManagement: 'Data Management',
    dataNote: 'Your data is entirely private and stored locally. Hard-deleting the app loses all data. Export regularly!',
    exportData: 'Export Data (Backup)', restoreData: 'Restore Data', importRestore: 'Import / Restore',
    nameAndDose: 'Name and dose required', selectAndAmount: 'Select medication and amount',
    enterIngredient: 'Enter ingredient name first.', medAndTime: 'Medication and time required',
    queryingFDA: 'Querying FDA database...', noBrandTrying: 'No brand match — trying active ingredient...',
    searchingWiki: 'Searching Wikipedia for ingredients...',
    genericMatch: 'Generic match', viaWiki: '📚 Via Wikipedia', doses: 'Dosen',
    notFoundFDA: 'Not found in FDA, Wikipedia, or generic databases.',
    saveAsTypedBtn: 'Save as "{n}"', linkIngredient: 'Optional: Ingredient for FDA data',
    ingredientPlaceholder: 'e.g. Rosuvastatin', fetchBtn: 'Fetch',
    adverseLabel: '⚠️ Main Adverse Events:', adverseVia: '⚠️ Main Adverse Events (via {ing}):',
    notFoundFDAShort: 'Not found in FDA either.',
    deleteMedConfirm: 'Delete medication?', loggedSuccess: 'Logged successfully!',
    removeScheduleConfirm: 'Remove schedule?', valueRequired: 'Value required',
    selectFile: 'Please select a file first.', restoredSuccess: 'Data successfully restored!',
    importError: 'Error reading backup file.', lookupFailed: 'Lookup failed. Check connection.',
    wikiIngredientFound: 'Wikipedia found ingredient: {ing}', translating: 'Translating...',
    unknown: 'Unknown', units: 'Units', pillUnit: 'Pill(s)', kg: 'kg',
    pillFormat: 'Pill', liquidFormat: 'Liquid', injectionFormat: 'Injection', inhalerFormat: 'Inhaler',
    detailsBtn: 'Details', editBtn: 'Edit', updateMedication: 'Edit Medication',
    sideEffectsTitle: '⚠️ Side Effects', frequency: 'Frequency', symptom: 'Symptom', close: 'Close',
    morning: 'Morning', noon: 'Noon', evening: 'Evening',
    daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', quarterly: 'Quarterly', everyXDays: 'Every X Days',
    dayIntervalLbl: 'Repeat every {x} days',
    searchStartpage: '🔍 Search on Startpage',
    searchAi: '🔍 AI Search',
    enteringApiKey: 'Grok API-Key',
    aiThinking: 'Grok thinking...',
    aiError: 'AI request failed.',
    settingsSavedLabel: 'Settings saved',
    saveSettingsBtn: 'Save Settings',
    missingKeyError: 'Please setup your Grok API-Key in settings first.',
    testingKey: 'Testing Key...',
    keyInvalid: 'Key invalid',
    modelIdLabel: 'Grok Model ID',
    modelSuggestion: 'Try: grok-4.20-non-reasoning or grok-2',
    fetchingModels: 'Loading models...',
    refreshModels: 'Refresh Models',
    customModel: 'Custom...',
    notFoundAiLabel: 'Medication not found or unknown.',
    selectMatch: 'Select match:',
    multipleFound: 'Multiple matches found',
    history: 'History',
    pulse: 'Pulse',
    glucose: 'Blood Glucose',
    linkMetrics: 'Link body metrics with this plan',
    pulseLabel: 'Pulse (bpm)',
    glucoseLabel: 'Glucose (mg/dL)',
    deleteAllData: 'Clear all project data',
    deleteLogs: 'Clear intake log only',
    resetTodayLbl: 'Reset today\'s plan',
    confirmDeleteAll: 'CRITICAL: DELETE ALL DATA (Meds, Plans, Logs)? This cannot be undone!',
    confirmDeleteLogs: 'Clear all intake/metric history?',
    metricRequired: 'Metric required',
    fillRequiredMetrics: 'Please enter required metrics.',
    anchorDate: 'Start Date',
    startWeekday: 'Weekday',
    startDayOfMonth: 'Day of Month',
    monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday',
    adHoc: 'Ad-hoc',
    analytics: 'Analytics',
    list: 'List',
    charts: 'Charts',
    adherence: 'Adherence',
    trends: 'Trends',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    lastYear: 'Last Year',
    missed: 'Missed',
    generateTestBtn: 'Add Test Data',
    clearTestBtn: 'Clear Test Data',
    testDataCount: 'Count: {n}',
    testDataNote: 'Test data is marked. Your personal entries stay safe when clearing test data.',
    upcomingEvents: 'Upcoming Events',
    doctorNotFoundAi: 'No doctor matching your criteria was found.',
    forceUpdateBtn: '📄 Force App Update (Clear Cache)',
    today: 'Today',
    tomorrow: 'Tomorrow',
    noUpcoming: 'No upcoming medications.',
    weeklyExport: 'Weekly Export (.ics)',
    addToCalendar: 'Reminder',
    calendarFileName: 'Medicine_Plan.ics',
    appointment: 'Doctor Appointment',
    medication: 'Medication',
    doctorName: 'Name, Practice or Clinic (Search & Auto-Fill)',
    location: 'Location / Address',
    phone: 'Phone Number',
    note: 'Notes',
    oneTime: 'One-time (Date & Time)',
    recurring: 'Recurring',
    doctorSearch: '✨ Find Doctor Online',
    regionPlaceholder: 'City or Postal Code',
    specialty: 'Specialty (Urology, GP, ...)',
    anySpecialty: 'Any Specialty',
    doctorSelect: 'Select Doctor',
    defaultRegionLabel: 'Default City / Region for AI Search',
    locating: 'Locating...',
    locErr: 'Location failed',
    specialties: [
      'General Practitioner', 'Internist', 'Cardiologist', 'Dentist', 'Urologist',
      'Gynecologist', 'Orthopedist', 'Dermatologist', 'Ophthalmologist', 'ENT',
      'Pediatrician', 'Neurologist', 'Psychiatrist'
    ],
    searchGoogle: 'Search on Google',
    aiAccuracyWarning: '⚠️ AI data can be hallucinated or outdated. Always verify before visiting!',
    liveSearchLabel: 'Enable Live AI Web Search',
    liveSearchSub: 'Requires grok-4.20-reasoning or grok-2. Provides 100% current data.',
    magicImportBtn: 'Magic Import',
    magicImportPlaceholder: 'Paste Google results or Link here...',
    magicImportInfo: 'AI will extract name, address and phone from text or URLs.',
    importing: 'Magic Importing...',
    autoSearchBtn: 'Auto-Search & Fill',
    autoSearchInfo: 'AI will search for the name above and find the address.',
    updateAvailable: 'Update Available',
    currentVersion: 'Current Version',
    newVersion: 'New Version',
    updateNow: 'Update Now',
    upToDate: 'App is up to date',
    diagTitle: 'System Diagnosis',
    diagKeyOk: 'API Key is functional',
    diagModelsFound: '{n} models found',
    diagSearchOk: 'Web Search is working',
    diagSearchErr: 'Web Search failed/not supported',
    diagModelRec: 'Recommendation: {m}',
    diagSpeed: 'Latency: {n}ms',
    diagTesting: 'Running diagnostics...',
    extendedInfo: 'Extended Info',
    hersteller: 'Manufacturer',
    einsatzgebiet: 'Area of Use',
    quickSelectArea: 'Search by Class:',
    chooseArea: '-- Choose Class --'
  },
  de: {
    settings: 'Einstellungen',
    home: 'Start', meds: 'Medikamente', logAction: 'Einnahme', plans: 'Pläne',
    dueToday: 'Heute fällig', noPlans: 'Keine Pläne vorhanden. Erstelle einen Plan!',
    noUpcoming: "Keine anstehenden Termine",
    recentActivity: "Kürzliche Aktivitäten",
    loggedActivity: 'Heutige Aktivität', noLogsToday: 'Noch keine Einnahme heute.',
    recentMetrics: 'Letzte Messwerte', noMetrics: 'Noch keine Messwerte eingetragen.',
    scheduled: 'Geplant', completed: '✅ Eingenommen', skipped: '❌ Übersprungen', skip: 'Überspringen', dueTodayBadge: '• Heute fällig', taken: 'eingenommen', weight: 'Gewicht',
    pastDue: 'Überfällig', missedTitle: 'Verpasste Termine',
    addMedication: 'Medikament hinzufügen', nameLbl: 'Name', defaultDose: 'Standarddosis', unitLbl: 'Einheit', formatLbl: 'Format',
    saveMedication: 'Medikament speichern', cancel: 'Abbrechen', yourMedications: 'Ihre Medikamente',
    noMedsFound: 'Keine Medikamente gefunden. Fügen Sie eines hinzu!', delete: 'Löschen', addBtn: '+ Hinzufügen',
    viewSideEffects: '⚠️ Nebenwirkungen', translateAdverse: '🌐 Auf Deutsch übersetzen',
    createSchedule: 'Plan erstellen', selectMed: 'Medikament wählen', timeOfDay: 'Uhrzeit',
    dose: 'Dosis', savePlan: 'Plan speichern', yourSchedule: 'Ihr Tagesplan',
    noSchedule: 'Kein Tagesplan erstellt.', remove: 'Entfernen', newPlan: '+ Neu',
    takes: 'Nimmt', at: 'um', appleCalendar: '+ Apple Kalender', chooseOption: '-- Bitte wählen --',
    addMedFirst: 'Zuerst ein Medikament hinzufügen.',
    logIntake: 'Einnahme erfassen', addMedFirst2: 'Bitte zuerst ein Medikament hinzufügen.',
    amountTaken: 'Eingenommene Menge', quantity: 'Menge', recordIntake: 'Einnahme speichern',
    logDateTime: 'Datum & Uhrzeit',
    otherMed: 'Anderes (Manuell)',
    logMetric: 'Körpermesswert erfassen', metricType: 'Messtyp', bodyWeight: 'Körpergewicht (kg)',
    bloodPressure: 'Blutdruck (mmHg)', valueLbl: 'Wert', saveMetric: 'Messwert speichern',
    dataManagement: 'Datenverwaltung',
    dataNote: 'Ihre Daten sind vollständig privat und lokal gespeichert. Beim Löschen der App gehen alle Daten verloren. Exportieren Sie Ihre Daten regelmäßig!',
    exportData: 'Daten exportieren (Sicherung)', restoreData: 'Daten wiederherstellen', importRestore: 'Importieren / Wiederherstellen',
    nameAndDose: 'Name und Dosis erforderlich', selectAndAmount: 'Bitte Medikament und Menge angeben',
    enterIngredient: 'Bitte zuerst einen Wirkstoffnamen eingeben.', medAndTime: 'Medikament und Uhrzeit erforderlich',
    queryingFDA: 'FDA-Datenbank wird abgefragt...', noBrandTrying: 'Kein Markenname — suche nach Wirkstoff...',
    searchingWiki: 'Wikipedia wird nach Wirkstoffen durchsucht...',
    genericMatch: 'Wirkstoff-Treffer', viaWiki: '📚 Via Wikipedia', doses: 'Dosen',
    notFoundFDA: 'Nicht in FDA, Wikipedia oder Wirkstoffdatenbank gefunden.',
    saveAsTypedBtn: '„{n}“ so speichern', linkIngredient: 'Optional: Wirkstoff eingeben für FDA-Daten',
    ingredientPlaceholder: 'z.B. Rosuvastatin', fetchBtn: 'Abrufen',
    adverseLabel: '⚠️ Hauptnebenwirkungen:', adverseVia: '⚠️ Hauptnebenwirkungen (via {ing}):',
    notFoundFDAShort: 'Auch in FDA nicht gefunden.',
    deleteMedConfirm: 'Medikament löschen?', loggedSuccess: 'Erfolgreich eingetragen!',
    removeScheduleConfirm: 'Tagesplan entfernen?', valueRequired: 'Wert erforderlich',
    selectFile: 'Bitte zuerst eine Datei wählen.', restoredSuccess: 'Daten erfolgreich wiederhergestellt!',
    importError: 'Fehler beim Lesen der Sicherungsdatei.', lookupFailed: 'Suche fehlgeschlagen. Verbindung prüfen.',
    wikiIngredientFound: 'Wikipedia hat Wirkstoff gefunden: {ing}', translating: 'Übersetze...',
    unknown: 'Unbekannt', units: 'Einheiten', pillUnit: 'Pille(n)', kg: 'kg',
    pillFormat: 'Pille', liquidFormat: 'Flüssigkeit', injectionFormat: 'Injektion', inhalerFormat: 'Inhalator',
    detailsBtn: 'Details', editBtn: 'Bearbeiten', updateMedication: 'Medikament bearbeiten',
    sideEffectsTitle: '⚠️ Nebenwirkungen', frequency: 'Häufigkeit', symptom: 'Symptom', close: 'Schließen',
    morning: 'Morgens', noon: 'Mittags', evening: 'Abends',
    daily: 'Täglich', weekly: 'Wöchentlich', monthly: 'Monatlich', quarterly: 'Vierteljährlich', everyXDays: 'Alle X Tage',
    dayIntervalLbl: 'Wiederhole alle {x} Tage',
    searchStartpage: '🔍 Auf Startpage suchen',
    searchAi: '🔍 KI-Suche',
    enteringApiKey: 'Grok API-Key',
    aiThinking: 'Grok denkt nach...',
    aiError: 'Fehler bei der KI-Abfrage.',
    settingsSavedLabel: 'Einstellungen gespeichert',
    saveSettingsBtn: 'Einstellungen speichern',
    missingKeyError: 'Bitte hinterlege zuerst deinen Grok API-Key in den Einstellungen.',
    testingKey: 'Key wird geprüft...',
    keyInvalid: 'Key ungültig',
    modelIdLabel: 'Grok Modell ID',
    modelSuggestion: 'Versuche: grok-4.20-non-reasoning oder grok-2',
    fetchingModels: 'Modelle werden geladen...',
    refreshModels: 'Modelle aktualisieren',
    customModel: 'Benutzerdefiniert...',
    notFoundAiLabel: 'Medikament nicht gefunden oder unbekannt.',
    selectMatch: 'Bitte Treffer wählen:',
    multipleFound: 'Mehrere Ergebnisse gefunden',
    history: 'Historie',
    pulse: 'Puls',
    glucose: 'Blutzucker',
    linkMetrics: 'Körpermesswerte mit diesem Plan verknüpfen',
    pulseLabel: 'Puls (bpm)',
    glucoseLabel: 'Blutzucker (mg/dL)',
    deleteAllData: 'Alle Projektdaten löschen',
    deleteLogs: 'Nur Einnahme-Log löschen',
    resetTodayLbl: 'Heutigen Tagesplan zurücksetzen',
    confirmDeleteAll: 'KRITISCH: ALLE Daten löschen (Medikamente, Pläne, Logs)? Dies kann nicht rückgängig gemacht werden!',
    confirmDeleteLogs: 'Alle Einnahme- und Messwert-Historien löschen?',
    metricRequired: 'Messung erforderlich',
    fillRequiredMetrics: 'Bitte trage die erforderlichen Messwerte ein.',
    anchorDate: 'Startdatum',
    startWeekday: 'Wochentag',
    startDayOfMonth: 'Tag des Monats',
    monday: 'Montag', tuesday: 'Dienstag', wednesday: 'Mittwoch', thursday: 'Donnerstag', friday: 'Freitag', saturday: 'Samstag', sunday: 'Sonntag',
    adHoc: 'Ad-hoc',
    analytics: 'Statistik',
    list: 'Liste',
    charts: 'Diagramme',
    adherence: 'Adhärenz',
    trends: 'Trends',
    last7Days: 'Letzte 7 Tage',
    last30Days: 'Letzte 30 Tage',
    lastYear: 'Letztes Jahr',
    missed: 'Vergessen',
    generateTestBtn: 'Testdaten hinzufügen',
    clearTestBtn: 'Testdaten löschen',
    testDataCount: 'Anzahl: {n}',
    testDataNote: 'Testdaten sind markiert. Deine persönlichen Einträge bleiben beim Löschen sicher.',
    upcomingEvents: 'Anstehende Termine',
    doctorNotFoundAi: 'Kein Arzt passend zu Ihren Kriterien gefunden.',
    forceUpdateBtn: '📄 App-Update erzwingen (Cache leeren)',
    today: 'Heute',
    tomorrow: 'Morgen',
    noUpcoming: 'Keine anstehenden Medikamente.',
    weeklyExport: 'Wochen-Export (.ics)',
    addToCalendar: 'Erinnerung',
    calendarFileName: 'Medikamente_Plan.ics',
    appointment: 'Arzt-Termin',
    medication: 'Medikament',
    doctorName: 'Arzt, Klinik oder Praxis (Suche & Auto-Fill)',
    location: 'Ort / Adresse',
    phone: 'Telefonnummer',
    note: 'Notizen',
    oneTime: 'Einmalig (Datum & Uhrzeit)',
    recurring: 'Regelmäßig',
    doctorSearch: '✨ Arzt im Internet suchen',
    regionPlaceholder: 'Ort oder Postleitzahl',
    specialty: 'Fachrichtung',
    anySpecialty: 'Keine Einschränkung (Alle)',
    doctorSelect: 'Arzt wählen',
    magicImportFallback: 'Manuell einfügen (Text/Link)',
    defaultRegionLabel: 'Standard Stadt / Region für KI-Suche',
    locating: 'Ortung...',
    locErr: 'Ortung fehlgeschlagen',
    extendedInfo: 'Erweiterte Infos',
    hersteller: 'Hersteller',
    einsatzgebiet: 'Einsatzgebiet',
    quickSelectArea: 'Nach Klasse suchen:',
    chooseArea: '-- Klasse wählen --',
    specialties: [
      'Allgemeinmediziner', 'Internist', 'Kardiologe', 'Zahnarzt', 'Urologe',
      'Gynäkologe', 'Orthopäde', 'Hautarzt', 'Augenarzt', 'HNO-Arzt',
      'Kinderarzt', 'Neurologe', 'Psychiater'
    ],
    searchGoogle: 'Auf Google suchen',
    aiAccuracyWarning: '⚠️ KI-Daten können erfunden oder veraltet sein. Bitte vor dem Besuch immer prüfen!',
    liveSearchLabel: 'Live KI-Websuche aktivieren',
    liveSearchSub: 'Erfordert grok-4.20-reasoning oder grok-2. Sorgt für 100% aktuelle Daten.',
    magicImportBtn: 'Magic Import',
    magicImportPlaceholder: 'Google-Ergebnis oder Link hier einfügen...',
    magicImportInfo: 'KI extrahiert Name, Adresse und Telefon aus Text oder Links.',
    importing: 'Magic Import läuft...',
    autoSearchBtn: 'Automatisch suchen & ausfüllen',
    autoSearchInfo: 'KI sucht nach dem oben eingegebenen Namen im Internet.',
    updateAvailable: 'Update verfügbar',
    currentVersion: 'Aktuelle Version',
    newVersion: 'Neue Version',
    updateNow: 'Jetzt aktualisieren',
    upToDate: 'App ist auf dem neuesten Stand',
    diagTitle: 'System-Diagnose',
    diagKeyOk: 'API-Key ist funktionsfähig',
    diagModelsFound: '{n} Modelle gefunden',
    diagSearchOk: 'Websuche funktioniert',
    diagSearchErr: 'Websuche fehlgeschlagen/nicht unterstützt',
    diagModelRec: 'Empfehlung: {m}',
    diagSpeed: 'Latenz: {n}ms',
    diagTesting: 'Diagnose läuft...',
  }
};

export const LOCAL_DRUG_KB = {
  'ezerosu': 'Rosuvastatin, Ezetimibe',
  'sortis': 'Atorvastatin',
  'crestor': 'Rosuvastatin',
  'pantozol': 'Pantoprazol',
  'pantoprazol': 'Pantoprazole',
  'voltaren': 'Diclofenac',
  'nexium': 'Esomeprazole',
  'ibumetin': 'Ibuprofen',
  'aspirin': 'Acetylsalicylic acid',
  'lasix': 'Furosemide',
  'concor': 'Bisoprolol',
  'thromboass': 'Acetylsalicylic acid',
  'plavix': 'Clopidogrel',
  'eliquis': 'Apixaban',
  'xarelto': 'Rivaroxaban',
  'l-thyroxin': 'Levothyroxine',
  'euthyrox': 'Levothyroxine',
  'metformin': 'Metformin',
  'januvia': 'Sitagliptin',
  'victoza': 'Liraglutide',
  'trulicity': 'Dulaglutide',
  'jardiance': 'Empagliflozin',
  'forxiga': 'Dapagliflozin',
  'ozempic': 'Semaglutide',
  'mounjaro': 'Tirzepatide',
  'ramipril': 'Ramipril',
  'lisinopril': 'Lisinopril',
  'amlodipin': 'Amlodipine',
  'candesartan': 'Candesartan',
  'valsartan': 'Valsartan',
  'olmesartan': 'Olmesartan',
  'metoprolol': 'Metoprolol',
  'nebivolol': 'Nebivolol',
  'carvedilol': 'Carvedilol',
  'spironolacton': 'Spironolactone',
  'hct': 'Hydrochlorothiazide',
  'simvastatin': 'Simvastatin',
  'pravastatin': 'Pravastatin',
  'atorvastatin': 'Atorvastatin',
  'ezetimib': 'Ezetimibe',
  'moxonidin': 'Moxonidine',
  'clonidin': 'Clonidine',
  'doxazosin': 'Doxazosin',
  'tamsulosin': 'Tamsulosin',
  'finasterid': 'Finasteride',
  'dutasterid': 'Dutasteride',
  'sildenafil': 'Sildenafil',
  'tadalafil': 'Tadalafil',
  'vardenafil': 'Vardenafil'
};
